sudo: required
dist: trusty
language: node_js
node_js:
  - "7"
install:
  - npm install -g eslint
  - npm install -g csslint
  - npm install stylelint
  - npm install stylelint-config-standard --save-dev
script:
  - npm run eslint
  - npm run csslint
  - mpm run stylelint
